-- إنشاء جدول الإعدادات للتحكم في الألوان
CREATE TABLE IF NOT EXISTS public.store_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- السماح بالوصول المجهول للقراءة (ضروري للزوار)
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
ON public.store_settings 
FOR SELECT 
TO public 
USING (true);

-- إدراج القيم الافتراضية إذا أردت
INSERT INTO public.store_settings (key, value) VALUES
('color_primary', '#A88F48'),
('color_bg', '#FDFCF0'),
('color_text', '#2B3024')
ON CONFLICT (key) DO NOTHING;
